#menu
[[main]]
    name = "Home"
    url = "/"
    weight = 1
    identifier = "home"
      [main.params]
          icon = "home"
          newTab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/dean534"

[social.params]
icon = "brand-github"